package com.rahul.project.gateway.model;

import javax.persistence.*;
import java.io.Serializable;

// Generated May 13, 2009 8:11:54 PM by Hibernate Tools 3.2.2.GA

/**
 * GcsgenericParamsM generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "GCSGENERICPARAMSM_SEQ", allocationSize = 50, sequenceName = "GCSGENERICPARAMSM_SEQ")
@Table(name = "GCSGENERIC_PARAMS_M")
public class GcsgenericParamsM implements Serializable {


    @Id
    @GeneratedValue(generator = "GCSGENERICPARAMSM_SEQ", strategy = GenerationType.SEQUENCE)
    @Column(name = "GEN_PARAMID")
    private Long genParamid;

    @Column(name = "GEN_PARAMETER_NAME")
    private String parameterName;

    @Column(name = "DESCRIPTION")
    private String description;

    @Column(name = "PARAMETER_VALUE")
    private String parameterValue;

    @Column(name = "CUSTOMER_CLASS")
    private String customerClass;

    @Column(name = "PARAM_DISPLAY_NAME")
    private String paramDisplayName;

    public GcsgenericParamsM() {
    }


    public Long getGenParamid() {
        return this.genParamid;
    }

    public void setGenParamid(Long genParamid) {
        this.genParamid = genParamid;
    }

    public String getParameterName() {
        return this.parameterName;
    }

    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getParameterValue() {
        return this.parameterValue;
    }

    public void setParameterValue(String parameterValue) {
        this.parameterValue = parameterValue;
    }

    public String getCustomerClass() {
        return this.customerClass;
    }

    public void setCustomerClass(String customerClass) {
        this.customerClass = customerClass;
    }

    public String getParamDisplayName() {
        return this.paramDisplayName;
    }

    public void setParamDisplayName(String paramDisplayName) {
        this.paramDisplayName = paramDisplayName;
    }
}
